version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: utn-api-fintech

    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: utn-api-fintech

    ports:
      - "3311:3306"

    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: